wandb_version: 1

LR:
  desc: null
  value: 0.0005
NUM_ENVS:
  desc: null
  value: 1024
NUM_STEPS:
  desc: null
  value: 128
TOTAL_TIMESTEPS:
  desc: null
  value: 100000.0
FC_DIM_SIZE:
  desc: null
  value: 128
GRU_HIDDEN_DIM:
  desc: null
  value: 128
UPDATE_EPOCHS:
  desc: null
  value: 4
NUM_MINIBATCHES:
  desc: null
  value: 4
GAMMA:
  desc: null
  value: 0.99
GAE_LAMBDA:
  desc: null
  value: 0.95
CLIP_EPS:
  desc: null
  value: 0.2
SCALE_CLIP_EPS:
  desc: null
  value: false
ENT_COEF:
  desc: null
  value: 0.01
VF_COEF:
  desc: null
  value: 0.5
MAX_GRAD_NORM:
  desc: null
  value: 0.5
ACTIVATION:
  desc: null
  value: relu
ENV_NAME:
  desc: null
  value: hanabi
SEED:
  desc: null
  value: 30
NUM_SEEDS:
  desc: null
  value: 2
ENV_KWARGS:
  desc: null
  value: {}
ANNEAL_LR:
  desc: null
  value: true
WANDB_MODE:
  desc: null
  value: disabled
ENTITY:
  desc: null
  value: ''
PROJECT:
  desc: null
  value: RL-Roguelike
NUM_ACTORS:
  desc: null
  value: 2048
NUM_UPDATES:
  desc: null
  value: 0.0
MINIBATCH_SIZE:
  desc: null
  value: 65536
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1735034595.032029
    t:
      1:
      - 12
      - 45
      - 50
      - 55
      2:
      - 12
      - 45
      - 50
      - 55
      3:
      - 16
      4: 3.10.12
      5: 0.16.0
      8:
      - 1
      - 5
      13: linux-x86_64
