wandb_version: 1

LR:
  desc: null
  value: 0.0005
NUM_ENVS:
  desc: null
  value: 128
NUM_STEPS:
  desc: null
  value: 128
TOTAL_TIMESTEPS:
  desc: null
  value: 10000000.0
UPDATE_EPOCHS:
  desc: null
  value: 4
NUM_MINIBATCHES:
  desc: null
  value: 4
GAMMA:
  desc: null
  value: 0.99
GAE_LAMBDA:
  desc: null
  value: 0.95
CLIP_EPS:
  desc: null
  value: 0.2
SCALE_CLIP_EPS:
  desc: null
  value: false
ENT_COEF:
  desc: null
  value: 0.01
VF_COEF:
  desc: null
  value: 0.5
MAX_GRAD_NORM:
  desc: null
  value: 0.5
ACTIVATION:
  desc: null
  value: relu
ENV_NAME:
  desc: null
  value: RL-Roguelike-JAXMARL
ANNEAL_LR:
  desc: null
  value: true
SEED:
  desc: null
  value: 30
ENV_KWARGS:
  desc: null
  value: {}
NUM_SEEDS:
  desc: null
  value: 2
WANDB_MODE:
  desc: null
  value: disabled
ENTITY:
  desc: null
  value: ''
PROJECT:
  desc: null
  value: RL-Roguelike
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1735038066.124188
    t:
      1:
      - 12
      - 45
      - 50
      - 55
      2:
      - 12
      - 45
      - 50
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.10.12
      5: 0.16.0
      8:
      - 1
      - 5
      13: linux-x86_64
